name: flagforge_flutter
description: Flutter SDK client for FlagForge, an open-source on-premise feature flagging platform. Supports prefetch, local cache, auto-refresh, and user targeting.
version: 0.1.0
homepage: https://github.com/Rollercoders/flagforge_flutter
repository: https://github.com/Rollercoders/flagforge_flutter

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0
  flutter_lints: ^4.0.0
